/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}", "./src/components/**/*.{vue,js,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["Montserrat", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        roboto: ["Roboto", "sans-serif"],
      },
      colors: {
        primary: "#6F5AF8",
        "primary-light": "#E7E3FF",
        "primary-lighter": "#F7F5FF",
        "primary-lightest": "#FDFCFF",
        "primary-hover": "#7F69FF",
        "primary-dark": "#5A47D1",
        "primary-darker": "#4835A8",
        secondary: "#4BCFFA",
        danger: "#E42933",
        "danger-light": "#FDEFEF",
        "danger-hover": "#D95353",
        "danger-darker": "#C21F2B",
        "accent-dark": "#4BCFFA",
        surface: {
          light: "#FFFFFF",
          dark: "#2A2B38",
        },
        background: {
          light: "#F8F9FA",
          dark: "#1F2029",
        },
        text: {
          light: "#1F2937",
          dark: "#F5F5F5",
          "secondary-light": "#4B5563",
          "secondary-dark": "#D1D5DB",
          "accent-light": "#6F5AF8",
          "accent-dark": "#4BCFFA",
          success: "#22C55E",
          "success-light": "#ECFDF5",
          "success-hover": "#16A34A",
          "success-dark": "#1B3A2A",
          "success-darker": "#15803D",
          info: "#4BCFFA",
          "info-light": "#E6F9FF",
          "info-hover": "#2BB7E6",
          "info-dark": "#123640",
          "info-darker": "#1DAED8",
          danger: "#E42933",
          "danger-light": "#FDEFEF",
          "danger-hover": "#D95353",
          "danger-dark": "#4C1C1E",
          "danger-darker": "#C21F2B",
          warning: "#F59E0B",
          "warning-light": "#FFFBEB",
          "warning-hover": "#D97706",
          "warning-dark": "#3B2A05",
          "warning-darker": "#B45309",
        },
        "gray-light": "#D1D5DB",
        "gray-lighter": "#F1F3F6",
        "gray-placeholder": "#9CA3AF",
        textfield: {
          empty: { light: "#F1F3F6", dark: "#2A2B38" },
          filled: { light: "#F7F5FF", dark: "#2A2B38" },
          error: { light: "#FDEFEF", dark: "#4C1C1E" },
          border: {
            light: "#D1D5DB",
            dark: "#D1D5DB",
            "error-light": "#E42933",
            "error-dark": "#C21F2B",
            "focused-border-light": "#6F5AF8",
            "focused-border-dark": "#5A47D1",
          },
          placeholder: {
            light: "#9CA3AF",
            dark: "#D1D5DB",
            "error-light": "#E42933",
            "error-dark": "#C21F2B",
          },
        },
        "select-options": {
          text: {
            light: "#1F2937",
            dark: "#F5F5F5",
            "selected-light": "#6F5AF8",
            "selected-dark": "#E7E3FF",
          },
          background: {
            light: "#FFFFFF",
            dark: "#2A2B38",
            "hovered-light": "#F1F3F6",
            "hovered-dark": "#3A3B4E",
            "selected-light": "#FDFCFF",
            "selected-dark": "#4835A8",
            "selected-hover-light": "#E7E3FF",
            "selected-hover-dark": "#5A47D1",
          },
        },
      },
      borderRadius: {
        prompt: "10px",
      },
      boxShadow: {
        card: "0 4px 12px rgba(0,0,0,0.1)",
        dropdown: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      },
    },
  },
  plugins: [],
};
