// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ConnectToDatabase(arg1:models.DBConnection):Promise<string>;

export function CreateConnection(arg1:models.CreateDBConnection):Promise<models.SaveDBConnectionResponse>;

export function DeleteConnection(arg1:number):Promise<void>;

export function DisconnectFromDatabase(arg1:number):Promise<string>;

export function GetActiveConnections():Promise<Array<models.ConnectionWithStatus>>;

export function GetConnections():Promise<Array<models.ConnectionWithStatus>>;

export function GetSupportedDatabases():Promise<Array<models.DatabaseDriver>>;

export function GetThemeConfig():Promise<models.ThemeConfig>;

export function IsConnected(arg1:number):Promise<boolean>;

export function ListTables(arg1:number,arg2:string):Promise<Array<models.Table>>;

export function ReadDroppedFile(arg1:string):Promise<string>;

export function Reload():Promise<void>;

export function RunQuery(arg1:number,arg2:string):Promise<Array<Record<string, any>>>;

export function SetTheme(arg1:boolean):Promise<void>;

export function TestConnection(arg1:models.CreateDBConnection,arg2:models.DatabaseDriver):Promise<string>;

export function UpdateConnection(arg1:models.DBConnection):Promise<models.SaveDBConnectionResponse>;
