// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetSupportedDatabases():Promise<Array<models.DatabaseDriver>>;

export function SetTheme(arg1:boolean):Promise<void>;

export function TestConnection(arg1:models.DBConnection):Promise<string>;
