// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateConnection(arg1:models.CreateDBConnection):Promise<models.SaveDBConnectionResponse>;

export function GetConnections():Promise<Array<models.DBConnection>>;

export function GetSupportedDatabases():Promise<Array<models.DatabaseDriver>>;

export function GetThemeConfig():Promise<models.ThemeConfig>;

export function Reload():Promise<void>;

export function SetTheme(arg1:boolean):Promise<void>;

export function TestConnection(arg1:models.CreateDBConnection,arg2:models.DatabaseDriver):Promise<string>;

export function UpdateConnection(arg1:models.DBConnection):Promise<models.SaveDBConnectionResponse>;
