// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToDatabase(arg1) {
  return window['go']['main']['App']['ConnectToDatabase'](arg1);
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DisconnectFromDatabase(arg1) {
  return window['go']['main']['App']['DisconnectFromDatabase'](arg1);
}

export function GetActiveConnections() {
  return window['go']['main']['App']['GetActiveConnections']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetSupportedDatabases() {
  return window['go']['main']['App']['GetSupportedDatabases']();
}

export function GetTableData(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetThemeConfig() {
  return window['go']['main']['App']['GetThemeConfig']();
}

export function IsConnected(arg1) {
  return window['go']['main']['App']['IsConnected'](arg1);
}

export function ListTables(arg1, arg2) {
  return window['go']['main']['App']['ListTables'](arg1, arg2);
}

export function ReadDroppedFile(arg1) {
  return window['go']['main']['App']['ReadDroppedFile'](arg1);
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}

export function RunQuery(arg1, arg2) {
  return window['go']['main']['App']['RunQuery'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}
